# repos:
#   # isort - Import sorting
#   - repo: https://github.com/pre-commit/mirrors-isort
#     rev: v5.12.0  # 使用 isort 的版本
#     hooks:
#       - id: isort
#         args: ["--profile", "black"]
# 
#   # black - Code formatter
#   - repo: https://github.com/psf/black
#     rev: 23.9b0  # 使用 black 的版本
#     hooks:
#       - id: black
# 
#   # flake8 - Code linting
#   - repo: https://github.com/pycqa/flake8
#     rev: 6.1.0  # 使用 flake8 的版本
#     hooks:
#       - id: flake8
#         args: ["--max-line-length=88", "--ignore=E203,W503"]
# 
#   # mypy - Static type checker
#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.5.1  # 使用 mypy 的版本
#     hooks:
#       - id: mypy
#         args: ["--ignore-missing-imports"]

repos:
  - repo: local
    hooks:
      # isort - Import sorting
      - id: isort
        name: isort (local)
        entry: venv\Scripts\isort.exe  # 指定虚拟环境中的 isort
        language: system
        types: [python]
        args: ["--profile", "black"]
        files: ^.*\.py$

      # black - Code formatter
      - id: black
        name: black (local)
        entry: venv\Scripts\black.exe  # 指定虚拟环境中的 black
        language: system
        types: [python]
        files: ^.*\.py$

      # flake8 - Code linting
      - id: flake8
        name: flake8 (local)
        entry: venv\Scripts\flake8.exe  # 指定虚拟环境中的 flake8
        language: system
        types: [python]
        args: ["--max-line-length=88", "--ignore=E203,W503"]
        files: ^.*\.py$

      # mypy - Static type checker
      - id: mypy
        name: mypy (local)
        entry: venv\Scripts\mypy.exe  # 指定虚拟环境中的 mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports"]
        files: ^.*\.py$

default_stages: [commit]  # 默认在 commit 阶段运行
